export const FETCH_PLANETS_DATA = 'FETCH_PLANETS_DATA';
export const FETCH_PLANETS_DATA_SUCCESS = 'FETCH_PLANETS_DATA_SUCCESS';

export const FETCH_PLANET_DETAILS_DATA = 'FETCH_PLANET_DETAILS_DATA'
export const FETCH_PLANET_DETAILS_DATA_SUCCESS = 'FETCH_PLANET_DETAILS_DATA_SUCCESS'

export const FETCH_FILMS_DATA = 'FETCH_FILMS_DATA';
export const FETCH_FILMS_DATA_SUCCESS = 'FETCH_FILMS_DATA_SUCCESS';

export const FETCH_RESIDENTS_DATA = 'FETCH_RESIDENTS_DATA';
export const FETCH_RESIDENTS_DATA_SUCCESS = 'FETCH_RESIDENTS_DATA_SUCCESS';