export const FETCH_PLANETS_DATA = 'FETCH_PLANETS_DATA';
export const FETCH_PLANETS_DATA_SUCCESS = 'FETCH_PLANETS_DATA_SUCCESS';

export const FETCH_PLANET_DETAILS_DATA = 'FETCH_PLANET_DETAILS_DATA'
export const FETCH_PLANET_DETAILS_DATA_SUCCESS = 'FETCH_PLANET_DETAILS_DATA_SUCCESS'